export const services = [
  {
    service: 'Привати',
    villager: '3',
    cosak: '5',
    hetman: '50',
  },
  {
    service: 'Домівки',
    villager: '3',
    cosak: '5',
    hetman: '50',
  },
  {
    service: 'Кількість лотів на аукціоні',
    villager: '3',
    cosak: '6',
    hetman: '24',
  },
  {
    service: 'Колір ніку',
    villager: 'WHITE',
    cosak: 'YELLOW',
    hetman: 'DARK PURPLE',
  },
  {
    service: '/hat',
    villager: 'НІ',
    cosak: 'ТАК',
    hetman: 'ТАК',
  },
  {
    service: '/wbench',
    villager: 'НІ',
    cosak: 'ТАК',
    hetman: 'ТАК',
  },
  {
    service: 'Плащ',
    villager: 'НІ',
    cosak: 'ТАК',
    hetman: 'ТАК',
  },
  {
    service: 'Ковадло',
    villager: 'НІ',
    cosak: 'ТАК',
    hetman: 'ТАК',
  },
  {
    service: 'Картографічний стіл',
    villager: 'НІ',
    cosak: 'ТАК',
    hetman: 'ТАК',
  },
  {
    service: 'Каменеріз',
    villager: 'НІ',
    cosak: 'ТАК',
    hetman: 'ТАК',
  },
  {
    service: 'Точило',
    villager: 'НІ',
    cosak: 'ТАК',
    hetman: 'ТАК',
  },
  {
    service: 'Ткацький верстат',
    villager: 'НІ',
    cosak: 'ТАК',
    hetman: 'ТАК',
  },
  {
    service: 'Стіл коваля',
    villager: 'НІ',
    cosak: 'ТАК',
    hetman: 'ТАК',
  },
  {
    service: 'Смітник',
    villager: 'НІ',
    cosak: 'ТАК',
    hetman: 'ТАК',
  },
  {
    service: 'Політ',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Скриня Енду',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Заряд полум\'я',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Вхід поза без черги',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Повернення на місце смерті',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Ремонт',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Зміна погоди',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Режим безсмертя',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Телепортація по кординатам',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Візуальні ефекти',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Елітра',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: 'Броня',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: 'ТАК',
  },
  {
    service: '/kit banners',
    villager: 'НІ',
    cosak: 'НІ',
    hetman: '2 РАЗИ',
  },
  {
    service: '/kit blocks',
    villager: 'НІ',
    cosak: '1 РАЗ',
    hetman: '6 РАЗИ',
  },
  {
    service: '/kit books',
    villager: 'НІ',
    cosak: '1 РАЗ',
    hetman: '6 РАЗИ',
  },
  {
    service: 'Прапорці привату',
    villager: 'НІ',
    cosak: 'БАЗОВІ',
    hetman: 'УСІ',
  }
];
