export enum Path {
  Home = '/',
  Rules = '/rules',
  Commands = '/commands',
  Complaints = '/complaints',
  FAQ = '/faq',
  About = '/about',
  History = '/history',
  PenaltyLog = '/penalty-log',
  Legends = '/legends',
  ReferalProgram = '/referal-program',
  Screenshots = '/screenshots',
  Donate = '/donate',
  Premium = '/premium',
  ChestShop = '/chest-shop',
  PCM = '/pcm',
  Map = '/map',
  NotFound = '*',
}
