export const commandList = [
  { value: '/spawn', description: 'Телепортація на спавн' },
  { value: '/home', description: 'Телепортує на точку відродження' },
  { value: '/tpa (нік)', description: 'Запит, на телепортацію до іншого гравця' },
  { value: '/tpaccept', description: 'Команда, що підтверджує запит, на телепортацію до вас іншого гравця' },
  { value: '/tpacancel', description: 'Відміняє запит, на телепортацію до іншого гравця' },
  { value: '/warp (назва)', description: 'Телепортує на точку варпу' },
  { value: '/rtp', description: 'Телепортує у випадкову точку на поверхні по основному світу' },
  { value: '/getpos', description: 'Дізнатися свої координати' },
  { value: '/ignore (нік)', description: 'Дозволяє перестати отримувати повідомлення від іншого гравця' },
  { value: '/kit (назва)', description: 'Отримати обраний за назвою набір предметів' },
  { value: '/kit list', description: 'Виводить у чаті список доступних наборів' },
  { value: '/warp list', description: 'Виводить у чат список доступних варпів' },
  { value: '/msg (нік)', description: 'Написати приватне повідомлення іншому гравцю' },
  { value: '/r', description: 'Швидко відповісти на приватне повідомлення іншого гравця' },
  { value: '/suicide', description: 'Померти у грі' },
  { value: '/near', description: 'Дізнатися, хто з гравців поруч з вами' },
  { value: '/delhome', description: 'Видаляє точку відродження' },
  { value: '//wand', description: 'Отримати дерев\'яну сокиру - інструмент для створення приватного регіону' },
  { value: '//expand', description: 'Команда, для розширення виділеного регіону' },
  { value: '/rg claim (назва)', description: 'Створює регіон з виділеної області для вашого привату з вашою назвою' },
  { value: '//pos1 //pos2', description: 'Створює виділення першої та другої позицї гравця' },
  { value: '//size', description: 'Виводить у чат розмір виділеного регіону' },
  { value: '//sel', description: 'Прибрати виділений регіон' },
  { value: '/rg info', description: 'Вивести інформацію про регіон' },
  { value: '//contract', description: 'Команда, для зменшення виділеного регіону' },
  { value: '/rg redefine', description: 'Перестворити регіон за новим виділенням' },
  { value: '/rg list', description: 'Виводить список створених регіонів' },
  { value: '/addmember (нік)', description: 'Надати доступ гравцю до свого привату' },
  { value: '//count', description: 'Підрахувати кількість блоків у виділеному регіоні' },
  { value: '/rg remove (назва)', description: 'Видалити регіон по назві' },
  { value: '/rg sel', description: 'Виділити регіон, в якому ви знаходитесь' },
  { value: '/rg removemember (нік)', description: 'Видаляє з регіона обраного гравця, доданого раніше' },
  { value: '/pvp', description: 'Можливість вимикати і вмикати стан ПВП на сервері' },
  { value: '/enderchest', description: 'Швидкий доступ до ендерскрині' },
  { value: '/feed', description: 'Повністю відновлює шкалу голоду гравця' },
  { value: '/heal', description: 'Повністю відновлює шкалу здоров\'я гравця' },
  { value: '/repair', description: 'Повністю ремонтує предмет, що в руках у гравця' },
  { value: '/workbench', description: 'Відкриває уявний верстак' },
  { value: '/setwarp (назва)', description: 'Встановлює точку варпу' },
  { value: '/sethome', description: 'Встановлює точку відродження' },
  { value: '/back', description: 'Повернутися назад на точку смерті або до поперадньої точки телепортації' },
];
